language: php
dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - vendor/bin/phpunit --verbose

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4
