language: php
dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - vendor/bin/phpunit --verbose

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
